### ISSUE TITLE
SSR support 

### ISSUE THREAD

**Issue by andrew-oko-odion** [shizpi/react-redux-permissions#11]
Does it support Server side rendering yet?
I really like your approach!

**Comment by andrew-oko-odion** [comment]
I am a great fan of Nextjs, 
wondering if I can use it with SSR.

**Comment by fabiulous** [comment]
@andrew-oko-odion Yes, there's nothing preventing you from using this with SSR.
But you need a way to set permissions in state before the server returns the response. With NextJs you'll need to use `getInitialProps`
